### PR TITLE
Don't import add_to_builtins on Django 1.9

### LINKED ISSUE #19: Support Django 1.9
`add_to_builtins` is deprecated and will be removed in 1.9.
https://docs.djangoproject.com/en/dev/releases/1.9/#django-template-base-add-to-builtins-is-removed

Must use a setting, so probably going to need a note in docs and a runtime warning? e.g. (not tested)

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'APP_DIRS': True,
            'OPTIONS': {
                'builtins': ['overextends.templatetags.overextends_tags'],
            }
        },
    ]

### PR DESCRIPTION
**Pull request by carltongibson**
Fixes #19

### CODE REVIEW

**Comment by stephenmcd** [comment]
Great, thank you!

**Comment by carltongibson** [comment]
No problem. Any chance you could push a PyPI release? (Ta!)

**Comment by stephenmcd** [comment]
Are you sure that's what you want?

Since 1.9 isn't released yet, a new release here wouldn't include any change to setup.py to allow it, which may cause some deployment problems.

**Comment by carltongibson** [comment]
@stephenmcd Not sure I see how that would happen? (The change is backwards compatible and we just tell `pip` what version we want no?)

**Comment by stephenmcd** [comment]
Yes the change itself is definitely fine and backward compatible.

I'm referring to deploying your project with this as a dependency while it specifies in setup.py that it doesn't work with Django 1.9 - I've seen this bite people before where they think they're deploying 1.9 for example, and a library (like this one) restricts them to 1.8. I honestly don't know if the issue is with pip or misconfigured dependencies by the user, but it happens.

Given that I don't think it makes sense to push a new version just with this change - I'd recommend specifying the commit on this repo as your dependency.

**Comment by carltongibson** [comment]
OK, interesting. I've not seen/noticed that. Will do as you say. Thanks.

**Comment by stefanw** [comment]
Django 1.9 is now released :fireworks:, so a PyPI release would be appreciated!

(Also, any deployment that doesn't fix their dependencies explicitly to specific version numbers seems broken to me.)

**Comment by stephenmcd** [comment]
See #23

**Pull request merged**
